---
title: "課程模組資訊"
description: |
  網頁內容依授課場合調整。
#author:
#  - name: Nora Jones 
#    url: https://example.com/norajones
#    affiliation: Spacely Sprockets
#    affiliation_url: https://example.com/spacelysprokets
# date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## 課程準備 Preparation

- 除大學生1年級，建議學員自備能執行本機版R與Rstudio的個人電腦或筆電。

- 參考[可重製研究操作教學套件](/seed_courses/)，了解符合個人狀況的學習進程。


## 先備或必學能力 Prerequisite Skill(s)


|學員身份|種子教師|研究生|大學生(2年級以上)|大學生(1年級)
|---|:---:|:---:|:---:|:---:|
|可運作的R & Rstudio| V | V | V | |
|更新R及R套件 | V | V | V | |
|github帳號 | V | V | V | V |
|git版本控制系統基本操作| V | V | V | |


## 學習目標 Objectives

### 種子教師

- 認識開放透明的研究規範
- 更新研究操作

### 研究生

- 認識開放透明的研究規範
- 學習開放透明的研究操作

### 大學生(2年級以上)

- 認識開放透明的研究規範
- 學習開放透明的研究操作

### 大學生(1年級)

- 學習能長期累積思考成品的寫作方法
- 認識基本機率論與計算工具
- 認識開放透明的研究規範


#### 課前自學影片

- 安裝R, Rstudio, 設定Git

<iframe width="560" height="315" src="https://www.youtube.com/embed/TRQbovHGLQk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


- 更新R核心環境

<iframe width="560" height="315" src="https://www.youtube.com/embed/u05IqPDQIOo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- 透過github repo創建專案

<iframe width="560" height="315" src="https://www.youtube.com/embed/yeLSkxtc-kI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



## 學習課表 Syllabus

### 種子教師

|進度編號|單元名稱|講義及課程資訊連結|
|:---:|:---:|:---:|
|0| 課程說明 | [啟動講義](/seed_courses/Lecture00.html) |
|1| 如何評估及解讀效果量 | [課程講義](/seed_courses/Lecture01.html) |
|1.1| 效果量R函式彙整協作 | 發佈於[成果驗收](tests.html) |
|2| 設計有高考驗力的研究 | [課程講義](/seed_courses/Lecture02.html) |
|2.1| 樣本數估計方案協作 | 發佈於[成果驗收](tests.html) |
|3| 評估已出版研究的考驗力 | [課程講義](/seed_courses/Lecture03.html) |
|3.1 | 整合分析方案協作 | 發佈於[成果驗收](tests.html) |

### 研究生

|進度編號|單元名稱|講義及課程資訊連結|
|:---:|:---:|:---:|
|0| 課程說明 | [啟動講義](/seed_courses/Lecture00.html) |
|1| 如何評估及解讀效果量 | [課程講義](/seed_courses/Lecture01.html) |
|2| Programming basics & Intro to R | 參考[增能課表](/seed_courses/Program_postgraudate.html) |
|3| Data Processing | 參考[增能課表](/seed_courses/Program_postgraudate.html) |
|4| Fundamental statistics | 參考[增能課表](/seed_courses/Program_postgraudate.html) |
|5| 設計有高考驗力的研究 | [課程講義](/seed_courses/Lecture02.html) |
|6| Advanced data analysis | 參考[增能課表](/seed_courses/Program_postgraudate.html) |
|7| Reproducible workflows | 參考[增能課表](/seed_courses/Program_postgraudate.html) |
|8| Advanced data processing |參考[增能課表](/seed_courses/Program_postgraudate.html) |
|9| Advanced data analysis | 參考[增能課表](/seed_courses/Program_postgraudate.html) |

### 大學生(2年級以上)

|進度編號|單元名稱|講義及課程資訊連結|
|:---:|:---:|:---:|
|0| 課程說明 | [啟動講義](/seed_courses/Lecture00.html) |
|1| Programming basics & Intro to R | 參考[增能課表](/seed_courses/Program_undergraudate.html) |
|2| Data Processing (Block 1) | 參考[增能課表](/seed_courses/Program_undergraudate.html) |
|3| Data processing (Block 2) | 參考[增能課表](/seed_courses/Program_undergraudate.html) |
|4| Probability | 參考[增能課表](/seed_courses/Program_undergraudate.html) |
|5|如何評估及解讀效果量 | [課程講義](/seed_courses/Lecture01.html) |
|6| Rmarkdown skill | 參考[增能課表](/seed_courses/Program_undergraudate.html) |
|7| Data processing (Block 3) | 參考[增能課表](/seed_courses/Program_undergraudate.html) |
|8| Probability distribution | 參考[增能課表](/seed_courses/Program_undergraudate.html) |
|9| NHST | 參考[增能課表](/seed_courses/Program_undergraudate.html) |
|10| Alpha, Power, Effect Sizes, Sample Size | 參考[增能課表](/seed_courses/Program_undergraudate.html) |
|11| Correlations and Regression | 參考[增能課表](/seed_courses/Program_undergraudate.html) |


* 20220216草稿版本
